#!/bin/sh

remote="$1"
url="$2"

ec=0
while read local_ref local_oid remote_ref remote_oid
do
	if test "$local_ref" = '(delete)'
	then continue
	fi

	#remote_ref_adj="$remote/${remote_ref#refs/heads/}"
	remote_ref_adj="upstream/master"

	git diff --name-only "$remote_ref_adj"..."$local_ref" -- apps/ |
		cut -d/ -f1-2 |
		uniq | (
			ec=0
			while read app; do
				if test -f "$app"; then continue; fi

				if git diff --quiet "$remote_ref_adj" "$local_ref" -- "$app"/metadata.json; then
					# no changes
					echo >&2 "$0: changes to $app, but no change to $app/metadata.json"
					ec=1
				fi
			done
			exit $ec
		)

	if test $? -ne 0; then
		ec=1
	fi
done

exit $ec
